### ISSUE TITLE
cmake install installs OpenXR SDK

### ISSUE THREAD

**Issue by ChristophHaag** [maluoi/openxr-explorer#2]
Because the OpenXR submodule has its own install target it gets installed too when installing openxr explorer

On Linux that's

- /usr/include/openxr/openxr.h
- /usr/include/openxr/openxr_platform.h
- /usr/include/openxr/openxr_platform_defines.h
- /usr/include/openxr/openxr_reflection.h
- /usr/lib/cmake/openxr/OpenXRConfig.cmake
- /usr/lib/cmake/openxr/OpenXRConfigVersion.cmake
- /usr/lib/cmake/openxr/OpenXRTargets-release.cmake
- /usr/lib/cmake/openxr/OpenXRTargets.cmake
- /usr/lib/libopenxr_loader.so
- /usr/lib/libopenxr_loader.so.1
- /usr/lib/libopenxr_loader.so.1.0.17
- /usr/lib/pkgconfig/openxr.pc
- /usr/share/doc/openxr/LICENSE

**Comment by maluoi** [comment]
Thanks for pointing this out! Your hint actually helped quite a bit. I've got a fix for this in the works, just gotta figure out some issues that fix brings up :)

**Comment by maluoi** [comment]
I haven't found a good way to fall back to the submodule if the OpenXR loader isn't installed, but I think this change should still be an improvement for you?

**Comment by maluoi** [comment]
Okay, I added a solution that I'm pretty happy with via CPM! (1bb4187aa081e752e587737791a408dd82bb0d67) I'll close this now, but feel free to re-open if I missed any issues with this approach :)
